-- MySQL schema for ECI Voting System
CREATE DATABASE IF NOT EXISTS eci_voting_system;
USE eci_voting_system;

CREATE TABLE IF NOT EXISTS assemblies (
    assembly_id INT AUTO_INCREMENT PRIMARY KEY,
    assembly_name VARCHAR(120) NOT NULL,
    district VARCHAR(120) NOT NULL,
    state VARCHAR(120) NOT NULL
);

-- Insert Karnataka 224 constituencies
INSERT INTO assemblies (assembly_name, district, state) VALUES
('Nippani','Nippani','Karnataka'),
('Chikkodi-Sadalga','Chikkodi-Sadalga','Karnataka'),
('Athani','Athani','Karnataka'),
('Kagwad','Kagwad','Karnataka'),
('Kudachi','Kudachi','Karnataka'),
('Raybag','Raybag','Karnataka'),
('Hukkeri','Hukkeri','Karnataka'),
('Arabhavi','Arabhavi','Karnataka'),
('Gokak','Gokak','Karnataka'),
('Yemkanmardi','Yemkanmardi','Karnataka'),
('Belagavi Uttar','Belagavi Uttar','Karnataka'),
('Belagavi Dakshin','Belagavi Dakshin','Karnataka'),
('Belagavi Rural','Belagavi Rural','Karnataka'),
('Khanapur','Khanapur','Karnataka'),
('Kittur','Kittur','Karnataka'),
('Bailhongal','Bailhongal','Karnataka'),
('Saundatti Yellamma','Saundatti Yellamma','Karnataka'),
('Ramdurg','Ramdurg','Karnataka'),
('Mudhol','Mudhol','Karnataka'),
('Terdal','Terdal','Karnataka'),
('Jamkhandi','Jamkhandi','Karnataka'),
('Bilgi','Bilgi','Karnataka'),
('Badami','Badami','Karnataka'),
('Bagalkot','Bagalkot','Karnataka'),
('Hungund','Hungund','Karnataka'),
('Muddebihal','Muddebihal','Karnataka'),
('Devar Hippargi','Devar Hippargi','Karnataka'),
('Basavana Bagewadi','Basavana Bagewadi','Karnataka'),
('Babaleshwar','Babaleshwar','Karnataka'),
('Bijapur City','Bijapur City','Karnataka'),
('Nagthan','Nagthan','Karnataka'),
('Indi','Indi','Karnataka'),
('Sindgi','Sindgi','Karnataka'),
('Afzalpur','Afzalpur','Karnataka'),
('Jewargi','Jewargi','Karnataka'),
('Shorapur','Shorapur','Karnataka'),
('Shahapur','Shahapur','Karnataka'),
('Yadgir','Yadgir','Karnataka'),
('Gurmitkal','Gurmitkal','Karnataka'),
('Chittapur','Chittapur','Karnataka'),
('Sedam','Sedam','Karnataka'),
('Chincholi','Chincholi','Karnataka'),
('Gulbarga Rural','Gulbarga Rural','Karnataka'),
('Gulbarga Dakshin','Gulbarga Dakshin','Karnataka'),
('Gulbarga Uttar','Gulbarga Uttar','Karnataka'),
('Aland','Aland','Karnataka'),
('Basavakalyan','Basavakalyan','Karnataka'),
('Homnabad','Homnabad','Karnataka'),
('Bidar South','Bidar South','Karnataka'),
('Bidar','Bidar','Karnataka'),
('Bhalki','Bhalki','Karnataka'),
('Aurad','Aurad','Karnataka'),
('Raichur Rural','Raichur Rural','Karnataka'),
('Raichur','Raichur','Karnataka'),
('Manvi','Manvi','Karnataka'),
('Devadurga','Devadurga','Karnataka'),
('Lingsugur','Lingsugur','Karnataka'),
('Sindhanur','Sindhanur','Karnataka'),
('Maski','Maski','Karnataka'),
('Kushtagi','Kushtagi','Karnataka'),
('Kanakagiri','Kanakagiri','Karnataka'),
('Gangawati','Gangawati','Karnataka'),
('Yelburga','Yelburga','Karnataka'),
('Koppal','Koppal','Karnataka'),
('Shirahatti','Shirahatti','Karnataka'),
('Gadag','Gadag','Karnataka'),
('Ron','Ron','Karnataka'),
('Nargund','Nargund','Karnataka'),
('Navalgund','Navalgund','Karnataka'),
('Kundgol','Kundgol','Karnataka'),
('Dharwad','Dharwad','Karnataka'),
('Hubli-Dharwad East','Hubli-Dharwad East','Karnataka'),
('Hubli-Dharwad Central','Hubli-Dharwad Central','Karnataka'),
('Hubli-Dharwad West','Hubli-Dharwad West','Karnataka'),
('Kalghatgi','Kalghatgi','Karnataka'),
('Haliyal','Haliyal','Karnataka'),
('Karwar','Karwar','Karnataka'),
('Kumta','Kumta','Karnataka'),
('Bhatkal','Bhatkal','Karnataka'),
('Sirsi','Sirsi','Karnataka'),
('Yellapur','Yellapur','Karnataka'),
('Hangal','Hangal','Karnataka'),
('Shiggaon','Shiggaon','Karnataka'),
('Haveri','Haveri','Karnataka'),
('Byadgi','Byadgi','Karnataka'),
('Hirekerur','Hirekerur','Karnataka'),
('Ranebennur','Ranebennur','Karnataka'),
('Hadagalli','Hadagalli','Karnataka'),
('Hagaribommanahalli','Hagaribommanahalli','Karnataka'),
('Vijayanagara','Vijayanagara','Karnataka'),
('Kampli','Kampli','Karnataka'),
('Siruguppa','Siruguppa','Karnataka'),
('Bellary','Bellary','Karnataka'),
('Bellary City','Bellary City','Karnataka'),
('Sandur','Sandur','Karnataka'),
('Kudligi','Kudligi','Karnataka'),
('Molakalmuru','Molakalmuru','Karnataka'),
('Challakere','Challakere','Karnataka'),
('Chitradurga','Chitradurga','Karnataka'),
('Hiriyur','Hiriyur','Karnataka'),
('Hosadurga','Hosadurga','Karnataka'),
('Holalkere','Holalkere','Karnataka'),
('Jagalur','Jagalur','Karnataka'),
('Harapanahalli','Harapanahalli','Karnataka'),
('Harihar','Harihar','Karnataka'),
('Davanagere North','Davanagere North','Karnataka'),
('Davanagere South','Davanagere South','Karnataka'),
('Mayakonda','Mayakonda','Karnataka'),
('Channagiri','Channagiri','Karnataka'),
('Honnali','Honnali','Karnataka'),
('Shimoga Rural','Shimoga Rural','Karnataka'),
('Bhadravati','Bhadravati','Karnataka'),
('Shimoga','Shimoga','Karnataka'),
('Tirthahalli','Tirthahalli','Karnataka'),
('Shikaripura','Shikaripura','Karnataka'),
('Sorab','Sorab','Karnataka'),
('Sagar','Sagar','Karnataka'),
('Byndoor','Byndoor','Karnataka'),
('Kundapura','Kundapura','Karnataka'),
('Udupi','Udupi','Karnataka'),
('Kapu','Kapu','Karnataka'),
('Karkal','Karkal','Karnataka'),
('Sringeri','Sringeri','Karnataka'),
('Mudigere','Mudigere','Karnataka'),
('Chikmagalur','Chikmagalur','Karnataka'),
('Tarikere','Tarikere','Karnataka'),
('Kadur','Kadur','Karnataka'),
('Chiknayakanhalli','Chiknayakanhalli','Karnataka'),
('Tiptur','Tiptur','Karnataka'),
('Turuvekere','Turuvekere','Karnataka'),
('Kunigal','Kunigal','Karnataka'),
('Tumkur City','Tumkur City','Karnataka'),
('Tumkur Rural','Tumkur Rural','Karnataka'),
('Koratagere','Koratagere','Karnataka'),
('Gubbi','Gubbi','Karnataka'),
('Sira','Sira','Karnataka'),
('Pavagada','Pavagada','Karnataka'),
('Madhugiri','Madhugiri','Karnataka'),
('Gauribidanur','Gauribidanur','Karnataka'),
('Bagepalli','Bagepalli','Karnataka'),
('Chikkaballapur','Chikkaballapur','Karnataka'),
('Sidlaghatta','Sidlaghatta','Karnataka'),
('Chintamani','Chintamani','Karnataka'),
('Srinivaspur','Srinivaspur','Karnataka'),
('Mulbagal','Mulbagal','Karnataka'),
('Kolar Gold Field','Kolar Gold Field','Karnataka'),
('Bangarapet','Bangarapet','Karnataka'),
('Kolar','Kolar','Karnataka'),
('Malur','Malur','Karnataka'),
('Yelahanka','Yelahanka','Karnataka'),
('K.R. Pura','K.R. Pura','Karnataka'),
('Byatarayanapura','Byatarayanapura','Karnataka'),
('Yeshwanthapura','Yeshwanthapura','Karnataka'),
('Rajarajeshwarinagar','Rajarajeshwarinagar','Karnataka'),
('Dasarahalli','Dasarahalli','Karnataka'),
('Mahalakshmi Layout','Mahalakshmi Layout','Karnataka'),
('Malleshwaram','Malleshwaram','Karnataka'),
('Hebbal','Hebbal','Karnataka'),
('Pulakeshinagar','Pulakeshinagar','Karnataka'),
('Sarvagnanagar','Sarvagnanagar','Karnataka'),
('C.V. Raman Nagar','C.V. Raman Nagar','Karnataka'),
('Shivajinagar','Shivajinagar','Karnataka'),
('Shanti Nagar','Shanti Nagar','Karnataka'),
('Gandhi Nagar','Gandhi Nagar','Karnataka'),
('Rajaji Nagar','Rajaji Nagar','Karnataka'),
('Govindraj Nagar','Govindraj Nagar','Karnataka'),
('Vijay Nagar','Vijay Nagar','Karnataka'),
('Chamrajpet','Chamrajpet','Karnataka'),
('Chickpet','Chickpet','Karnataka'),
('Basavanagudi','Basavanagudi','Karnataka'),
('Padmanabhanagar','Padmanabhanagar','Karnataka'),
('B.T.M Layout','B.T.M Layout','Karnataka'),
('Jayanagar','Jayanagar','Karnataka'),
('Mahadevapura','Mahadevapura','Karnataka'),
('Bommanahalli','Bommanahalli','Karnataka'),
('Bangalore South','Bangalore South','Karnataka'),
('Anekal','Anekal','Karnataka'),
('Hosakote','Hosakote','Karnataka'),
('Devanahalli','Devanahalli','Karnataka'),
('Doddaballapur','Doddaballapur','Karnataka'),
('Nelamangala','Nelamangala','Karnataka'),
('Magadi','Magadi','Karnataka'),
('Ramanagaram','Ramanagaram','Karnataka'),
('Kanakapura','Kanakapura','Karnataka'),
('Channapatna','Channapatna','Karnataka'),
('Malavalli','Malavalli','Karnataka'),
('Maddur','Maddur','Karnataka'),
('Melukote','Melukote','Karnataka'),
('Mandya','Mandya','Karnataka'),
('Srirangapatna','Srirangapatna','Karnataka'),
('Nagamangala','Nagamangala','Karnataka'),
('Krishnarajpet','Krishnarajpet','Karnataka'),
('Shravanabelagola','Shravanabelagola','Karnataka'),
('Arsikere','Arsikere','Karnataka'),
('Belur','Belur','Karnataka'),
('Hassan','Hassan','Karnataka'),
('Holenarasipur','Holenarasipur','Karnataka'),
('Arkalgud','Arkalgud','Karnataka'),
('Sakleshpur','Sakleshpur','Karnataka'),
('Belthangady','Belthangady','Karnataka'),
('Moodabidri','Moodabidri','Karnataka'),
('Mangalore City North','Mangalore City North','Karnataka'),
('Mangalore City South','Mangalore City South','Karnataka'),
('Mangalore','Mangalore','Karnataka'),
('Bantval','Bantval','Karnataka'),
('Puttur','Puttur','Karnataka'),
('Sullia','Sullia','Karnataka'),
('Madikeri','Madikeri','Karnataka'),
('Virajpet','Virajpet','Karnataka'),
('Piriyapatna','Piriyapatna','Karnataka'),
('Krishnarajanagara','Krishnarajanagara','Karnataka'),
('Hunsur','Hunsur','Karnataka'),
('Heggadadevankote','Heggadadevankote','Karnataka'),
('Nanjangud','Nanjangud','Karnataka'),
('Chamundeshwari','Chamundeshwari','Karnataka'),
('Krishnaraja','Krishnaraja','Karnataka'),
('Chamaraja','Chamaraja','Karnataka'),
('Narasimharaja','Narasimharaja','Karnataka'),
('Varuna','Varuna','Karnataka'),
('T. Narasipur','T. Narasipur','Karnataka'),
('Hanur','Hanur','Karnataka'),
('Kollegal','Kollegal','Karnataka'),
('Chamarajanagar','Chamarajanagar','Karnataka'),
('Gundlupet','Gundlupet','Karnataka');

CREATE TABLE IF NOT EXISTS voters (
    voter_id VARCHAR(20) PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    age INT NOT NULL,
    gender ENUM('Male','Female','Other') DEFAULT 'Male',
    assembly_id INT NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    has_voted BOOLEAN DEFAULT FALSE,
    verified_status BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (assembly_id)
    REFERENCES assemblies(assembly_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS candidates (
    candidate_id INT AUTO_INCREMENT PRIMARY KEY,
    candidate_name VARCHAR(150) NOT NULL,
    party_name VARCHAR(100) NOT NULL,
    assembly_id INT NOT NULL,
    symbol VARCHAR(100) NOT NULL,
    verified_by_eci BOOLEAN DEFAULT TRUE,
    added_by_admin BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (assembly_id)
    REFERENCES assemblies(assembly_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS votes (
    vote_id INT AUTO_INCREMENT PRIMARY KEY,
    voter_id VARCHAR(20) NOT NULL,
    candidate_id INT NOT NULL,
    assembly_id INT NOT NULL,
    vote_time DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (voter_id)
    REFERENCES voters(voter_id)
    ON DELETE CASCADE,

    FOREIGN KEY (candidate_id)
    REFERENCES candidates(candidate_id)
    ON DELETE CASCADE,

    FOREIGN KEY (assembly_id)
    REFERENCES assemblies(assembly_id)
    ON DELETE CASCADE,

    UNIQUE KEY unique_vote(voter_id)
);

CREATE TABLE IF NOT EXISTS admin (
    admin_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS election_status (
    election_id INT AUTO_INCREMENT PRIMARY KEY,
    assembly_id INT NOT NULL UNIQUE,
    election_started BOOLEAN DEFAULT FALSE,
    election_stopped BOOLEAN DEFAULT FALSE,
    result_declared BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (assembly_id)
    REFERENCES assemblies(assembly_id)
    ON DELETE CASCADE
);
